name: Named Tuple and Dictionary Profile and Company Data Analysis

'on':
  - push
  - repository_dispatch

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install Faker
          pip install numpy

      - name: Run Profile Tests Named Tuple
        id: test_named_tuple_profile
        uses: classroom-resources/autograding-python-grader@v1
        with:
          timeout: 10
          max-score: 250
          test-command: |
            python -m pip install --upgrade pip
            pip install pytest
            pip install Faker
            pip install numpy
            pip install -r requirements.txt

      - name: Run Profile Tests Dictionary
        id: test_dictionary_profile
        uses: classroom-resources/autograding-python-grader@v1
        with:
          timeout: 10
          max-score: 250
          setup-command: |
            python -m pip install --upgrade pip
            pip install pytest
            pip install Faker
            pip install numpy
            pip install -r requirements.txt

      - name: Run Company Tests
        id: test_company
        uses: classroom-resources/autograding-python-grader@v1
        with:
          timeout: 10
          max-score: 500
          setup-command: |
            python -m pip install --upgrade pip
            pip install pytest
            pip install Faker
            pip install numpy
            pip install -r requirements.txt


      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        env:
          TEST_RESULTS: "${{ steps.test_named_tuple_profile.outputs.result }},${{ steps.test_dictionary_profile.outputs.result }},${{ steps.test_company.outputs.result }}"
