name: Autograding Tests
'on':
  - push
  - repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: test_company
        id: test_company
        uses: classroom-resources/autograding-python-grader@v1
        with:
          timeout: 10
          max-score: 500
          setup-command: |
            pip install pytest
            pip install Faker
            pip install -r requirements.txt


      # - name: Autograding Reporter
      #   uses: classroom-resources/autograding-grading-reporter@v1
      #   env:
      #     TEST_COMPANY_RESULTS: "${{ steps.test_company.outputs.result }}"
      
      - name: Decode and assert python-test
        uses: actions/github-script@v6
        with:
          github-token: ${{ github.token || 'act' }}
          script: |
            // Decode the Base64 output
            const decodedResult = Buffer.from("${{ steps.test_company.outputs.result }}", 'base64').toString('utf8');
            console.log(`Decoded Result: ${decodedResult}`);
