name: Named Tuple and Dictionary Profile and Company Data Analysis

'on':
  - push
  - repository_dispatch

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install Faker
          pip install numpy

      - name: Run Profile Tests Named Tuple
        id: test_profiles_named_tuple
        uses: classroom-resources/autograding-python-grader@v1
        with:
          timeout: 10
          max-score: 250
          test-command: pytest test_named_tuple_profile.py -v

      - name: Run Profile Tests Dictionary
        id: test_profiles_dictionary
        uses: classroom-resources/autograding-python-grader@v1
        with:
          timeout: 10
          max-score: 250
          test-command: pytest test_dictionary_profile.py -v

      - name: Run Company Tests
        id: test_company
        uses: classroom-resources/autograding-python-grader@v1
        with:
          timeout: 10
          max-score: 250
          test-command: pytest test_company.py -v

      - name: Run Compare Dictionary and Named Tuple Tests
        id: test_compare_dictionary_named_tuple
        uses: classroom-resources/autograding-python-grader@v1
        with:
          timeout: 10
          max-score: 0
          test-command: python compare_dictionary_named_tuple.py

      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        env:
          TEST_RESULTS: "${{ steps.test_profiles_named_tuple.outputs.result }},${{ steps.test_profiles_dictionary.outputs.result }},${{ steps.test_company.outputs.result }},${{ steps.test_compare_dictionary_named_tuple.outputs.result }}"
