name: Named Tuple and Dictionary

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt
          pip install Faker
          pip install numpy

      - name: Run tests with autograding
        uses: classroom-resources/autograding-python-grader@v1
        with:
          test_files: |
            test_company.py:500
            test_dictironary_profile.py:250
            test_named_tuple_profile.py:250
          total_score: 1000  # Total possible score
